'use strict';

export const EPISODE_REQUEST = 'EPISODE_REQUEST';
export const EPISODE_RECEIVED = 'EPISODE_RECEIVED';
export const EPISODE_FAILURE = 'EPISODE_FAILURE';
export const EPISODE_UPDATE_REQUESTED = 'EPISODE_UPDATE_REQUESTED';
export const EPISODE_UPDATE_SUCCESSFUL = 'EPISODE_UPDATE_SUCCESSFUL';
export const EPISODE_UPDATE_FAILURE = 'EPISODE_UPDATE_FAILURE';

export const EPISODE_UPDATED = 'EPISODE_UPDATED';
export const EDIT_EPISODE = 'EDIT_EPISODE';

